version: "3.9"

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: journal_db
      POSTGRES_USER: journal_admin
      POSTGRES_PASSWORD: journalpass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U journal_admin -d journal_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - my-network

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DEBUG=True
      - DB_NAME=journal_db
      - DB_USER=journal_admin
      - DB_PASSWORD=journalpass
      - DB_HOST=db
      - DB_PORT=5432
    networks:
      - my-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@personaljournal.com # Replace with your email
      PGADMIN_DEFAULT_PASSWORD: personaljournal003  # Replace with your password
    ports:
      - "5050:80"  # Expose pgAdmin on localhost:5050
    depends_on:
      - db
    networks:
      - my-network

  pytest:
    image: python:3.9 # Use Python base image
    volumes:
      - .:/app
    command: >
      bash -c "pip install pytest && pytest"
    depends_on:
      - db
      - web
    networks:
      - my-network

volumes:
  postgres_data:

networks:
  my-network:
    driver: bridge